### PR TITLE
fix fill_v_value with new ndk optimizations

### PR DESCRIPTION
**Pull request by pulsarrush**
ndk 25c optimizations will realise some characters can not change so it will include partly plaintext strings

### CODE REVIEW

**Comment by liudongmiao** [comment]
why we need this ...? is there any attribute to make ndk doesn't optimize this at all?

**Comment by pulsarrush** [comment]
this is needed to use "-O2" but it looks like "-Oz" still works correctly

**Comment by pulsarrush** [comment]
do you think this is worth it to keep "-O2" working?

**Comment by liudongmiao** [comment]
could you try use another method, like:

```
m = sdk > 0 ? realm : 0;
```

Just make sure sdk is a runtime result.

**Pull request closed without merging**
